version: '3.8'

services:
  db-main:
    image: postgres:16-alpine
    container_name: postcribe_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postcribe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db-ai:
    image: postgres:16-alpine
    container_name: postcribe_db_ai
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postcribe_ai
    ports:
      - "5433:5432"
  
  redis:
    image: redis:7-alpine
    container_name: postcribe_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 